In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [7]:
a.itemsize

4

In [8]:
a.size

15

In [9]:
b = np.array(1,2,3,4)    # WRONG
b = np.array([1,2,3,4]) 

ValueError: only 2 non-keyword arguments accepted

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [10]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [12]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [13]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [14]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [15]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = a-b
c

array([20, 29, 38, 47])

In [17]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [18]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [19]:
a<35

array([ True,  True, False, False])